### PR TITLE
SQM-17 Entity type expressions

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by sebersole** [comment]
This seems to be covering a lot of different things: collection functions, entity-type expressions.  Can you separate these into distinction branches?

The reason being that I think there is a better way to handle entity-type checks.  But I'd first like to isolate the changes here to the stuff specifically related to that change.  The change I am contemplating is a basic tenant of designing a parser that I learned over time... Basically, whenever possible it is best to interpret things based on a syntactical analysis versus a semantical analysis.

**Comment by gunnarmorling** [comment]
Hi, actually all of this related to the entity type expression feature. The
change around collections is just an extraction of the sub-elements of
jpaCollectionFunction into separate rules which I did to make the map key
and value funtions usable within entity expressions (which JPA allows
AFAICS). That specific change is insulated in the second commit, it may
help to look at that one separately.

**Comment by sebersole** [comment]
So my idea is based on a few premises.  

First, the JPA spec only allows this in the WHERE clause.  So these "entity type expressions" (the JPA term, section 4.6.17.5) are only allowed as a predicate.  And specifically in conjunction with a limited set of predicate operators (=, <>, IN, NOT IN).  

The above premises come directly from the JPA spec.  Another premise I have is that one of the expressions in the predicate has to be a TYPE function; all other forms really would not make sense.  Bearing in mind that an "entity type expression" can be either (a) a TYPE function expression, (b) a parameter or (c) a entity-type-literal and leaving operator out of the equation for now, we'd have the following combinations:

* typeFunction & typeFunction
* typeFunction & parameter
* typeFunction & entityTypeLiteral
* parameter & entityTypeLiteral

I argue that the last one makes no sense to allow.  We can debate this one.  But it is an important premise to the idea to recognize these expressions syntactically.  Why?  Because notice how, if we strip away the last combination, all the remaining combinations have at least one typeFunction expression.  That would allow us to set up a special branch in the predicate rule to recognize this.  

Why is this such an important distinction (syntactic versus semantic)?  In a word, performance.  Specifically here: time, speed.  The approach you took (validating each token text as an entity name) is valid, and it works.  But you have to realize that every token/context we ask Antlr to evaluate as an expression will now involve a call to check whether the thing is an entity (so a series of method calls and eventually *at least* 2 Map lookups); for every possible thing that could evaluate as an expression.  

What is better, generally speaking, is to recognize that an expression *should be* an entity-type-expression based on syntax.  The *should be* is important.  Because now we move into syntactic analysis and semantic validation.  So if during parsing we are able to recognize that this expression should be an entityTypeExpression, we can later validate that it is as we walk the parse tree.  That will be a much more efficient check, because its limited.

Hopefully that makes sense.

**Comment by sebersole** [comment]
Any word on the requested changes?

**Comment by sebersole** [comment]
Going to close this.  I have added a note to the 6.0 todo doc (in the ORM repo, on the 6.0 working branch) regarding testing/implementing the combination stuff discussed above.

**Pull request closed without merging**
